#!/usr/bin/env python3
"""
Setup script for ZIEL-MAS API configuration
Helps users configure required API keys for actual functionality
"""

import os
import sys
from pathlib import Path

def setup_env_file():
    """Setup .env file with API keys"""
    
    print("🚀 ZIEL-MAS API Configuration Setup")
    print("=" * 50)
    
    # Check if .env exists
    env_path = Path(".env")
    if env_path.exists():
        print("⚠️  .env file already exists")
        choice = input("Do you want to overwrite it? (y/N): ").lower()
        if choice != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📝 To get REAL results instead of mock data, you need to configure API keys.")
    print("\n🔑 REQUIRED: GLM API Key")
    print("   Get your free API key from: https://open.bigmodel.cn/")
    print("   This is the main AI model used for intent parsing and code generation")
    
    # Get GLM API key
    glm_key = input("\nEnter your GLM API key (or press Enter to skip): ").strip()
    
    if not glm_key:
        print("\n❌ WARNING: No GLM API key provided!")
        print("   The system will use pattern matching and mock responses.")
        print("   To get real AI-powered results, get an API key from https://open.bigmodel.cn/")
        
        choice = input("Continue anyway? (y/N): ").lower()
        if choice != 'y':
            print("Setup cancelled.")
            return
    else:
        print("✅ GLM API key provided")
    
    # Optional API keys
    print("\n📧 OPTIONAL: Email Configuration (for sending emails)")
    smtp_user = input("Gmail address (or press Enter to skip): ").strip()
    smtp_password = None
    if smtp_user:
        smtp_password = input("Gmail app password (or press Enter to skip): ").strip()
        if smtp_password:
            print("✅ Email configuration provided")
    
    print("\n📱 OPTIONAL: WhatsApp Configuration (for WhatsApp messages)")
    twilio_sid = input("Twilio Account SID (or press Enter to skip): ").strip()
    twilio_token = None
    if twilio_sid:
        twilio_token = input("Twilio Auth Token (or press Enter to skip): ").strip()
        if twilio_token:
            print("✅ WhatsApp configuration provided")
    
    # Create .env file
    env_content = f"""# ZIEL-MAS Configuration
# Generated by setup_api_keys.py

# Backend Configuration
BACKEND_PORT=8000
BACKEND_HOST=0.0.0.0

# Database Configuration
MONGODB_URI=mongodb://localhost:27017/ziel_mas
REDIS_URI=redis://localhost:6379/0

# JWT Configuration
JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
JWT_ALGORITHM=HS256
JWT_EXPIRATION=86400

# Encryption
ENCRYPTION_KEY=your-32-byte-encryption-key-here-change-this

# GLM API Configuration
GLM_API_KEY={glm_key or 'your-glm-api-key-here'}
GLM_API_URL=https://api.glm.ai/v1

# Email Configuration
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER={smtp_user or ''}
SMTP_PASSWORD={smtp_password or ''}

# WhatsApp Configuration
TWILIO_ACCOUNT_SID={twilio_sid or ''}
TWILIO_AUTH_TOKEN={twilio_token or ''}
TWILIO_WHATSAPP_NUMBER=whatsapp:+14155238886

# Security
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
RATE_LIMIT_ENABLED=true
RATE_LIMIT_PER_MINUTE=60

# Execution Configuration
MAX_EXECUTION_TIME=3600
MAX_RETRIES=3
RETRY_BACKOFF=2

# Monitoring
LOG_LEVEL=INFO
ENABLE_AUDIT_LOGS=true
"""
    
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print(f"\n✅ .env file created successfully!")
        print(f"   Location: {env_path.absolute()}")
        
        if glm_key:
            print("\n🎉 Configuration complete!")
            print("   Your ZIEL-MAS system will now use REAL AI-powered responses.")
            print("   Restart the server to apply changes.")
        else:
            print("\n⚠️  Configuration completed with mock data.")
            print("   Add your GLM API key to .env file to get real AI responses.")
        
        print("\n📖 Next steps:")
        print("   1. Start MongoDB and Redis services")
        print("   2. Run: python -m backend.main")
        print("   3. Test with: python test.py")
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {e}")
        sys.exit(1)

def check_configuration():
    """Check current configuration"""
    
    print("🔍 Checking ZIEL-MAS Configuration")
    print("=" * 40)
    
    # Check .env file
    env_path = Path(".env")
    if not env_path.exists():
        print("❌ .env file not found")
        print("   Run: python setup_api_keys.py")
        return
    
    print("✅ .env file found")
    
    # Load and check GLM API key
    try:
        with open(env_path, 'r') as f:
            content = f.read()
        
        if 'GLM_API_KEY=your-glm-api-key-here' in content:
            print("⚠️  GLM API key not configured")
            print("   System will use mock responses")
        elif 'GLM_API_KEY=' in content and len(content.split('GLM_API_KEY=')[1].split('\n')[0].strip()) > 20:
            print("✅ GLM API key configured")
        else:
            print("❓ GLM API key configuration unclear")
        
        # Check other configurations
        configs = {
            'SMTP_USER': 'Email',
            'TWILIO_ACCOUNT_SID': 'WhatsApp'
        }
        
        for key, name in configs.items():
            if key in content and len(content.split(f'{key}=')[1].split('\n')[0].strip()) > 0:
                print(f"✅ {name} configured")
            else:
                print(f"⚪ {name} not configured (optional)")
                
    except Exception as e:
        print(f"❌ Error reading .env file: {e}")

def main():
    """Main setup function"""
    
    if len(sys.argv) > 1 and sys.argv[1] == 'check':
        check_configuration()
        return
    
    setup_env_file()

if __name__ == "__main__":
    main()
